server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  config:
    activate:
      on-profile: default
  application:
    name: pizza-write
    zipkin: http://zipkin:9411
  datasource:
    platform: postgres
    url: jdbc:postgresql://${pizzeberus_db:localhost}:5432/postgres
    username: postgres
    password: admin123
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

resilience4j:
  circuitbreaker:
    configs:
      shared:
        sliding-window-type: count_based # Counter-based
        sliding-window-size: 5 # Number of failed petitions allowed
        slow-call-rate-threshold: 50 # Percentage we will allow of failed or slow petitions
        permitted-number-of-calls-in-half-open-state: 1 # Number of petitions allowed in the half-open state
        max-wait-duration-in-half-open-state: 10s # Max duration time of the half-open state
        wait-duration-in-open-state: 10s # Time duration open-state
        writable-stack-trace-enabled: true # Console logs
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      pizza-write:
        base-config: shared